name: check_new_release
run-name: Check new Zabbix release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Prepare environment
      run: |
          python -m pip install --upgrade pip
          pip install requests
          apt install -y tee tail
    - name: Check new Zabbix release
      run: |
          ./.github/scripts/check_new_zabbx_release.py | tee /tmp/import.log
    - name: Send report
      if: steps.import_templates.outcome == 'failure'
      env:
        TBOT_TOKEN: ${{ secrets.TBOT_TOKEN }}
        TBOT_CHAT: ${{ vars.TBOT_CHAT }}
        SUBJECT: Found new Zabbix release
      run: tail /tmp/import.log | ./.github/scripts/telegram_msg.py
